// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szfgdinncqlpyvbfimxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6ZmdkaW5uY3FscHl2YmZpbXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDAzNzgsImV4cCI6MjA1ODExNjM3OH0.1-wtQZ7lC-AOGG6TL9z7UuS9YWCwhw58AgWN3vEw_a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);